### ISSUE TITLE
Fix package descriptions for IntelliJ Platform fat JARs

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/tool-base#106]
Now descriptions have this:

<img width="563" alt="image" src="https://github.com/user-attachments/assets/5e09fdfc-61ca-41f7-b882-1623de26aaf5">

We do provide module descriptions via Gradle API, but GitHub picks up something else. We had this problem for some other modules.  @armiol should have details on the root cause of the issue.

**Comment by armiol** [comment]
Looks like GitHub Packages randomly picks some descriptions from the repacked JARs.

I have just manually cleared these descriptions on Packages' side. So closing it for now.
